### ISSUE TITLE
Magic Lamp Animation?

### ISSUE THREAD

**Issue by AcidRain9** [helloSystem/KWin#1]
Magic Lamp Animation should be considered a default for maximizing and minimizing the applications.

If it is planned, then

I highly suggest considering adding

https://github.com/zzag/kwin-effects-yet-another-magic-lamp
By default, with the shape curve set to Bezier.

**Comment by probonopd** [comment]
Hello @AcidRain9, in the continuous builds there _should_ already be such an animation by default - is it not working?

**Comment by probonopd** [comment]
Tested on https://github.com/helloSystem/ISO/releases/tag/experimental-12.2, works for me.
