### ISSUE TITLE
The special effect of closing the window is weird

### ISSUE THREAD

**Issue by louies0623** [helloSystem/KWin#12]
https://github.com/helloSystem/ISO/assets/44593430/5a6e4157-96cf-4d2d-9090-138756b07ddc

CX62
0I38 Live

**Comment by probonopd** [comment]
Duplicate of https://github.com/helloSystem/KWin/issues/14

**Comment by probonopd** [comment]
Intel GPU, correct?

**Comment by louies0623** [comment]
yes

**Comment by probonopd** [comment]
Should be fixed now, can you confirm?

**Comment by louies0623** [comment]
is fix
