### ISSUE TITLE
Glitch in top-left corner

### ISSUE THREAD

**Issue by probonopd** [helloSystem/KWin#2]
![](https://user-images.githubusercontent.com/57624443/124600211-70e3a480-dea1-11eb-8d24-98e1e657d99a.jpg)

According to `#kwin` on IRC, the picture that should appear there is "in the Plasma theme". Which we are not using...

**Comment by probonopd** [comment]
Similarly, snapping windows to screen edges does not work.

**Comment by probonopd** [comment]
Solved by

```
# Glow effect when mouse moves to upper-left corner
mkdir -p ./KWin.app/Resources/share/plasma/desktoptheme/default/widgets/
cp /usr/local/share/plasma/desktoptheme/default/widgets/glowbar.svgz ./KWin.app/Resources/share/plasma/desktoptheme/default/widgets/
# Window snap effect preview
cp /usr/local/share/plasma/desktoptheme/default/widgets/translucentbackground.svgz ./KWin.app/Resources/share/plasma/desktoptheme/default/widgets/
```

Thanks @Pointedstick for the pointer :+1: I would never have started looking in `/usr/local/share/plasma` rather than in `/usr/local/share/kwin`.

**Comment by Pointedstick** [comment]
Yeah, this graphic comes from the active Plasma theme, but KWin should maybe have a fallback effect to handle the case where there are no Plasma themes installed because the DE is something other than Plasma. Can you file an upstream bug report about that?

**Comment by probonopd** [comment]
https://bugs.kde.org/show_bug.cgi?id=442639

**Comment by Pointedstick** [comment]
Thanks!

**Comment by probonopd** [comment]
The issue reappeared.

`KWin.app/Resources/share/plasma/desktoptheme/default/widgets/` seems to be wrong, it now apparently has to be `KWin.app/Resources/share/plasma/desktoptheme/widgets/` (without `default`).

This at least fixes the active corners, but the animation for the "Aero snap" still [doesn't work](https://github.com/helloSystem/KWin/issues/10) (`truss` shows that it is looking for some `...plasma/core...` file).

**Comment by louies0623** [comment]
If the red dot becomes white next to it, will it be repaired?
![image](https://github.com/helloSystem/KWin/assets/44593430/86268044-99f3-4e00-b5bb-6afe5388f721)

**Comment by probonopd** [comment]
Is it still broken in the latest build? If yes, do you know how to fix it?

**Comment by louies0623** [comment]
It's broken in version 9.0 and still exists without the breeze theme installed. I'm thinking it might be a KWin issue.
